/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    '@tiptap/react', 
    '@tiptap/pm', 
    '@tiptap/extension-link', 
    '@tiptap/starter-kit', 
    '@tiptap/extension-color', 
    '@tiptap/extension-text-align',
    '@tiptap/core',
    '@tiptap/extension-heading',
    '@tiptap/extension-highlight',
    '@tiptap/extension-underline',
    'axios',
    'throttle-debounce',
    'react-toastify',
    '@heroui/react',
    'dompurify',
    '@tiptap/extension-dropcursor',
    '@tiptap/extension-text',
    '@tiptap/extension-code-block',
    '@tiptap/extension-list-item',
    '@tiptap/extension-paragraph',
    '@tiptap/extension-ordered-list',
    '@tiptap/extension-gapcursor',
    '@tiptap/extension-strike',
    '@tiptap/extension-history',
    '@tiptap/extension-horizontal-rule',
    'compute-scroll-into-view',
    '@tiptap/extension-bubble-menu',
    '@tiptap/extension-italic',
    '@tiptap/extension-bold',
    '@tiptap/extension-blockquote',
    'js-cookie',
    '@tiptap/extension-bullet-list',
    '@tiptap/extension-code',
    '@tiptap/extension-hard-break',
    '@tiptap/extension-floating-menu',
    '@tiptap/extension-document',
    'prosemirror-state',
    'rc-util',
    'rc-pagination',
    'rc-menu',
    'rc-picker',
    'rc-table',
    'rc-select',
    'rc-notification',
    'rc-dialog',
    'rc-input-number',
    'rc-motion',
    'rc-dropdown',
    'rc-tooltip',
    'rc-checkbox',
    'rc-progress',
    'rc-textarea',
    'rc-input',
    'rc-switch',
    'rc-field-form',
    'rc-tree',
    'rc-resize-observer',
    'rc-drawer',
    'rc-upload',
    'rc-rate',
    'rc-tabs',
    '@ant-design/icons-svg',
    '@ant-design/icons',
    '@ant-design/colors',
    '@ant-design/cssinjs',
    '@ant-design/cssinjs-utils',
    '@ant-design/fast-color',
    '@ant-design/v5-patch-for-react-19',
    '@rc-component/color-picker'
  ],
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.experiments = {
        ...config.experiments,
        topLevelAwait: true,
      };
    }
    return config;
  }
}

module.exports = nextConfig
